### ISSUE TITLE
Submit test coverage to Coveralls.io

### ISSUE THREAD

**Issue by egasimus** [hackbg/ganesha#4]
1. Tests run locally but fail in CI - fix that
2. Figure out how to expose the coveralls repo token to [`node-tap`](https://www.npmjs.com/package/tap), which [seems to handle the rest automatically](https://node-tap.org/docs/coverage/)

**Comment by mradkov** [comment]
Lets integrate Codecov as it provides better overview of the coverage straight into the PR.
